settings:
  # Radius to search for items to merge
  merge-radius: 5.0
  # Maximum stack size per entity (Vanilla is 64, we support more!)
  max-stack-size: 128
  # Delay (in ticks) before attempting to stack newly spawned items.
  # Helps performance during explosions or breaking containers.
  stack-delay-ticks: 5
  
  # Prevent mobs from picking up items?
  prevent-mob-pickup: true
  
  # Mobs allowed to pickup items (keep VILLAGER for breeding)
  pickup-whitelist:
    - "VILLAGER"
    
  # Disable features in specific worlds
  disabled-worlds:
    - "spawn_hub"

# Limits the number of item entities per chunk to prevent lag machines.
chunk-limit:
  enabled: true
  # Maximum number of item entities allowed in a chunk.
  max-items: 64

visuals:
  glowing:
    enabled: true
    # Items will glow if stack amount is greater than this value
    threshold: 32

blacklist:
  # Items to NEVER stack (e.g. rare items)
  materials:
    - "NETHER_STAR"
    - "DRAGON_EGG"
    - "BEACON"
  
  # Advanced: Don't stack items with these NBT keys
  # Compatible with MMOItems ("MMOITEMS_ITEM_ID"), MythicMobs, etc.
  nbt-tags:
    - "MMOITEMS_ITEM_ID"
    - "MYTHIC_TYPE"

sounds:
  # Sound when player picks up item
  pickup:
    enabled: true
    sound: "ENTITY_EXPERIENCE_ORB_PICKUP"
    volume: 0.3
    pitch: 1.0

custom-name:
  # Show holograms above items?
  enabled: true
  # Format: {name} = Item Name, {amount} = Count
  # Color codes (&) supported.
  format: "{name} &cx{amount}"